[0m19:21:48.559338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ef0d0684f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ef0cea53880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ef0cea53820>]}


============================== 19:21:48.561816 | dfd244e6-e06e-485f-9368-d6690712c027 ==============================
[0m19:21:48.561816 [info ] [MainThread]: Running with dbt=1.8.4
[0m19:21:48.562306 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/cliente/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:21:48.568281 [info ] [MainThread]: dbt version: 1.8.4
[0m19:21:48.568686 [info ] [MainThread]: python version: 3.10.12
[0m19:21:48.569023 [info ] [MainThread]: python path: /usr/bin/python3
[0m19:21:48.569337 [info ] [MainThread]: os info: Linux-6.5.0-44-generic-x86_64-with-glibc2.35
[0m19:21:48.627621 [info ] [MainThread]: Using profiles dir at /home/cliente/.dbt
[0m19:21:48.628084 [info ] [MainThread]: Using profiles.yml file at /home/cliente/.dbt/profiles.yml
[0m19:21:48.628403 [info ] [MainThread]: Using dbt_project.yml file at /home/cliente/Code/RIO/Desafio CIVITAS Data Engineer/dbt_project.yml
[0m19:21:48.628845 [info ] [MainThread]: adapter type: postgres
[0m19:21:48.629150 [info ] [MainThread]: adapter version: 1.8.2
[0m19:21:48.629456 [info ] [MainThread]: Configuration:
[0m19:21:48.629748 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m19:21:48.630037 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m19:21:48.630322 [info ] [MainThread]: Required dependencies:
[0m19:21:48.630625 [debug] [MainThread]: Executing "git --help"
[0m19:21:48.632281 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m19:21:48.632725 [debug] [MainThread]: STDERR: "b''"
[0m19:21:48.633040 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m19:21:48.633353 [info ] [MainThread]: Connection:
[0m19:21:48.633705 [info ] [MainThread]:   host: localhost
[0m19:21:48.634014 [info ] [MainThread]:   port: 5432
[0m19:21:48.634415 [info ] [MainThread]:   user: userrio
[0m19:21:48.634864 [info ] [MainThread]:   database: adm_terceirizados_fed
[0m19:21:48.635292 [info ] [MainThread]:   schema: dbt_schema
[0m19:21:48.635628 [info ] [MainThread]:   connect_timeout: 10
[0m19:21:48.635939 [info ] [MainThread]:   role: None
[0m19:21:48.636240 [info ] [MainThread]:   search_path: None
[0m19:21:48.636539 [info ] [MainThread]:   keepalives_idle: 0
[0m19:21:48.636836 [info ] [MainThread]:   sslmode: None
[0m19:21:48.637134 [info ] [MainThread]:   sslcert: None
[0m19:21:48.637430 [info ] [MainThread]:   sslkey: None
[0m19:21:48.637728 [info ] [MainThread]:   sslrootcert: None
[0m19:21:48.638027 [info ] [MainThread]:   application_name: dbt
[0m19:21:48.638323 [info ] [MainThread]:   retries: 1
[0m19:21:48.638776 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m19:21:48.640329 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m19:21:48.652996 [debug] [MainThread]: Using postgres connection "debug"
[0m19:21:48.653477 [debug] [MainThread]: On debug: select 1 as id
[0m19:21:48.653808 [debug] [MainThread]: Opening a new connection, currently in state init
[0m19:21:48.666210 [debug] [MainThread]: SQL status: SELECT 1 in 0.012 seconds
[0m19:21:48.667254 [debug] [MainThread]: On debug: Close
[0m19:21:48.667685 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m19:21:48.668060 [info ] [MainThread]: [31m1 check failed:[0m
[0m19:21:48.668484 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/cliente/Code/RIO/Desafio CIVITAS Data Engineer/dbt_project.yml> not found

[0m19:21:48.669848 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.16925535, "process_user_time": 1.368812, "process_kernel_time": 0.060211, "process_mem_max_rss": "100388", "process_in_blocks": "8", "process_out_blocks": "16", "command_success": false}
[0m19:21:48.670518 [debug] [MainThread]: Command `dbt debug` failed at 19:21:48.670405 after 0.17 seconds
[0m19:21:48.670885 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m19:21:48.671294 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ef0d0684f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ef0ce7ed570>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ef0ce7db220>]}
[0m19:21:48.671697 [debug] [MainThread]: Flushing usage events
[0m19:34:32.603070 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b91077b1330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b9105b7fdf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b9105b7fd90>]}


============================== 19:34:32.605906 | 4dd8e1e5-1946-45e7-b7df-71aaba835547 ==============================
[0m19:34:32.605906 [info ] [MainThread]: Running with dbt=1.8.4
[0m19:34:32.606482 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/cliente/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m19:34:32.607053 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/cliente/Code/RIO/Desafio CIVITAS Data Engineer/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:34:32.607808 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.0839508, "process_user_time": 1.32623, "process_kernel_time": 0.055925, "process_mem_max_rss": "86384", "process_in_blocks": "288", "process_out_blocks": "16", "command_success": false}
[0m19:34:32.608453 [debug] [MainThread]: Command `dbt run` failed at 19:34:32.608348 after 0.08 seconds
[0m19:34:32.608871 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b91077b1330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b9105b7fe80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7b9105b7fdc0>]}
[0m19:34:32.609287 [debug] [MainThread]: Flushing usage events
[0m22:13:59.261742 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e35a94da860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e35a7bf1360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e35a7bf1300>]}


============================== 22:13:59.267567 | 478092df-4ea9-4735-9e7a-968b915bbf6c ==============================
[0m22:13:59.267567 [info ] [MainThread]: Running with dbt=1.8.4
[0m22:13:59.269082 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/cliente/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m22:13:59.270054 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/cliente/Code/RIO/Desafio CIVITAS Data Engineer/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:13:59.271394 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.07834598, "process_user_time": 1.433495, "process_kernel_time": 0.110583, "process_mem_max_rss": "85172", "process_in_blocks": "36040", "process_out_blocks": "8", "command_success": false}
[0m22:13:59.272258 [debug] [MainThread]: Command `dbt run` failed at 22:13:59.272127 after 0.08 seconds
[0m22:13:59.272748 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e35a94da860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e35a7bf13f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e35a7bf1330>]}
[0m22:13:59.273241 [debug] [MainThread]: Flushing usage events
[0m18:44:40.799886 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aed372ce6b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aed359fd1b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aed359fd150>]}


============================== 18:44:40.802326 | f057f10d-2d48-4069-87f1-18f131d83a44 ==============================
[0m18:44:40.802326 [info ] [MainThread]: Running with dbt=1.8.4
[0m18:44:40.802853 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/cliente/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --vars database: prefect_server', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:44:40.803392 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/cliente/Code/RIO/desafio_data_eng/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:44:40.804137 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.054569148, "process_user_time": 1.152109, "process_kernel_time": 0.036003, "process_mem_max_rss": "103856", "process_in_blocks": "16", "process_out_blocks": "8", "command_success": false}
[0m18:44:40.804749 [debug] [MainThread]: Command `dbt run` failed at 18:44:40.804645 after 0.06 seconds
[0m18:44:40.805154 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aed372ce6b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aed359fd240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aed359fd180>]}
[0m18:44:40.805559 [debug] [MainThread]: Flushing usage events
[0m21:32:04.665145 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7073846226b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707382d511e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707382d51180>]}


============================== 21:32:04.667788 | 63447020-b70d-4d2a-8497-01d3d5a8d031 ==============================
[0m21:32:04.667788 [info ] [MainThread]: Running with dbt=1.8.4
[0m21:32:04.668370 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/cliente/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select transformed', 'send_anonymous_usage_stats': 'True'}
[0m21:32:04.668932 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/cliente/Code/RIO/desafio_data_eng/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:32:04.669736 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.060864676, "process_user_time": 1.162058, "process_kernel_time": 0.043926, "process_mem_max_rss": "85480", "process_in_blocks": "16", "process_out_blocks": "16", "command_success": false}
[0m21:32:04.670395 [debug] [MainThread]: Command `dbt run` failed at 21:32:04.670284 after 0.06 seconds
[0m21:32:04.670823 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7073846226b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707382d51270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707382d511b0>]}
[0m21:32:04.671254 [debug] [MainThread]: Flushing usage events
[0m21:40:10.072143 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77056d42e6e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77056bb5d210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77056bb5d1b0>]}


============================== 21:40:10.074745 | 8e10011f-aa14-4b48-a9c4-82c16459fb4d ==============================
[0m21:40:10.074745 [info ] [MainThread]: Running with dbt=1.8.4
[0m21:40:10.075356 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/cliente/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select transformed', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:40:10.075909 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/cliente/Code/RIO/desafio_data_eng/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:40:10.076746 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.059295792, "process_user_time": 1.341825, "process_kernel_time": 0.067889, "process_mem_max_rss": "85632", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m21:40:10.077384 [debug] [MainThread]: Command `dbt run` failed at 21:40:10.077279 after 0.06 seconds
[0m21:40:10.077820 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77056d42e6e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77056bb5d2a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77056bb5d1e0>]}
[0m21:40:10.078244 [debug] [MainThread]: Flushing usage events
